
my_app_mail_succ:
    path: /succ
    defaults: { _controller: CdlrmailBundle:Mail:index }
my_app_mail_form:
    path: /mail
    defaults: { _controller: CdlrmailBundle:Mail:new }
my_app_mail_sendpage:
    path: /sendmail
    defaults: { _controller: CdlrmailBundle:Mail:sendMail }