coursvideo:
    path:     /
    defaults: { _controller: "CdlrcodeBundle:CoursVideo:index" }

coursvideo_show:
    path:     /{id}/show
    defaults: { _controller: "CdlrcodeBundle:CoursVideo:show" }

coursvideo_new:
    path:     /new
    defaults: { _controller: "CdlrcodeBundle:CoursVideo:new" }

coursvideo_create:
    path:     /create
    defaults: { _controller: "CdlrcodeBundle:CoursVideo:create" }
    requirements: { _method: post }

coursvideo_edit:
    path:     /{id}/edit
    defaults: { _controller: "CdlrcodeBundle:CoursVideo:edit" }

coursvideo_update:
    path:     /{id}/update
    defaults: { _controller: "CdlrcodeBundle:CoursVideo:update" }
    requirements: { _method: post|put }

coursvideo_delete:
    path:     /{id}/delete
    defaults: { _controller: "CdlrcodeBundle:CoursVideo:delete" }
    requirements: { _method: post|delete }
