rendezvous:
    path:     /
    defaults: { _controller: "CdlrcodeBundle:RendezVous:index" }

rendezvous_show:
    path:     /{id}/show
    defaults: { _controller: "CdlrcodeBundle:RendezVous:show" }

rendezvous_new:
    path:     /new
    defaults: { _controller: "CdlrcodeBundle:RendezVous:new" }

rendezvous_create:
    path:     /create
    defaults: { _controller: "CdlrcodeBundle:RendezVous:create" }
    requirements: { _method: post }

rendezvous_edit:
    path:     /{id}/edit
    defaults: { _controller: "CdlrcodeBundle:RendezVous:edit" }

rendezvous_update:
    path:     /{id}/update
    defaults: { _controller: "CdlrcodeBundle:RendezVous:update" }
    requirements: { _method: post|put }

rendezvous_delete:
    path:     /{id}/delete
    defaults: { _controller: "CdlrcodeBundle:RendezVous:delete" }
    requirements: { _method: post|delete }
