services:
#    cdlr_user.example:
#        class: Cdlr\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    cdlr_user.registration.form.type:
        class: Cdlr\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: cdlr_user_registration }
    redirect.after.login:
        class: Cdlr\UserBundle\Redirection\AfterLoginRedirection
        arguments: [@router]